defaults:
  domain: net-sec.local
  dns:
    - 8.8.8.8
    - 8.8.4.4

master-1:
  vip:
    - address: 10.20.10.20
      network: mgmt
    - address: 10.20.11.20
      network: serv
  mgmt:
    interface: enp3s0f0
    address: 10.20.10.21
    gateway: 10.20.10.1
  serv: 
    interface: enp3s0f1
    address: 10.20.11.21
    gateway: 10.20.11.1
  sync:
    interface: enp4s0f0
    address: 10.20.12.21
    gateway: 10.20.12.1

master-2:
  vip:
    - address: 10.20.10.20
      network: mgmt
    - address: 10.20.11.20
      network: serv
  mgmt:
    interface: enp3s0f0
    address: 10.20.10.22
    gateway: 10.20.10.1
  serv: 
    interface: enp3s0f1
    address: 10.20.11.22
    gateway: 10.20.11.1
  sync:
    interface: enp4s0f0
    address: 10.20.12.22
    gateway: 10.20.12.1

master-3:
  vip:
    - address: 10.20.10.20
      network: mgmt
    - address: 10.20.11.20
      network: serv
  mgmt:
    interface: enp3s0f0
    address: 10.20.10.23
    gateway: 10.20.10.1
  serv: 
    interface: enp3s0f1
    address: 10.20.11.23
    gateway: 10.20.11.1
  sync:
    interface: enp4s0f0
    address: 10.20.12.23
    gateway: 10.20.12.1


agent-1:
  mgmt:
    interface: enp4s0f0
    address: 10.20.10.41
    gateway: 10.20.10.1
  serv:
    interface: enp4s0f1
    address: 10.20.11.41
    gateway: 10.20.11.1
  sync:
    interface: enp4s0f2
    address: 10.20.12.41
    gateway: 10.20.12.1

agent-2:
  mgmt:
    interface: enp4s0f0
    address: 10.20.10.42
    gateway: 10.20.10.1
  serv:
    interface: enp4s0f1
    address: 10.20.11.42
    gateway: 10.20.11.1
  sync:
    interface: enp4s0f2
    address: 10.20.12.42
    gateway: 10.20.12.1

agent-3:
  mgmt:
    interface: enp4s0f0
    address: 10.20.10.43
    gateway: 10.20.10.1
  serv:
    interface: enp4s0f1
    address: 10.20.11.43
    gateway: 10.20.11.1
  sync:
    interface: enp4s0f2
    address: 10.20.12.43
    gateway: 10.20.12.1

agent-4:
  mgmt:
    interface: enp4s0f0
    address: 10.20.10.44
    gateway: 10.20.10.1
  serv:
    interface: enp4s0f1
    address: 10.20.11.44
    gateway: 10.20.11.1
  sync:
    interface: enp4s0f2
    address: 10.20.12.44
    gateway: 10.20.12.1