defaults:
  domain: test.local
  dns:
    - 8.8.8.8
    - 8.8.4.4

master-1:
  vip:
    - address: 192.168.43.20
      network: serv
  serv:
    interface: enp0s3
    address: 192.168.43.21
    gateway: 192.168.43.1
  mgmt: 
    interface: enp0s9
    address: 10.20.11.21
    gateway: 10.20.11.1
  sync:
    interface: enp0s10
    address: 10.20.12.21
    gateway: 10.20.12.1

master-2:
  vip:
    - address: 192.168.43.20
      network: serv
  serv:
    interface: enp0s3
    address: 192.168.43.22
    gateway: 192.168.43.1
  mgmt: 
    interface: enp0s9
    address: 10.20.11.22
    gateway: 10.20.11.1
  sync:
    interface: enp0s10
    address: 10.20.12.22
    gateway: 10.20.12.1

master-3:
  vip:
    - address: 192.168.43.20
      network: serv
  serv:
    interface: enp0s3
    address: 192.168.43.23
    gateway: 192.168.43.1
  mgmt: 
    interface: enp0s9
    address: 10.20.11.23
    gateway: 10.20.11.1
  sync:
    interface: enp0s10
    address: 10.20.12.23
    gateway: 10.20.12.1


agent-1:
  serv:
    interface: enp0s3
    address: 192.168.43.41
    gateway: 192.168.43.1
  mgmt: 
    interface: enp0s9
    address: 10.20.11.41
    gateway: 10.20.11.1
  sync:
    interface: enp0s10
    address: 10.20.12.41
    gateway: 10.20.12.1

agent-2:
  serv:
    interface: enp0s3
    address: 192.168.43.42
    gateway: 192.168.43.1
  mgmt: 
    interface: enp0s9
    address: 10.20.11.42
    gateway: 10.20.11.1
  sync:
    interface: enp0s10
    address: 10.20.12.42
    gateway: 10.20.12.1